include:
  - board: xiao_ble
    shield: Noctus_R rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: Noctus_L rgbled_adapter
  - board: xiao_ble
    shield: settings_reset